// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcersrwirsrmvmflbkfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjZXJzcndpcnNybXZtZmxia2ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNDg4ODMsImV4cCI6MjA3MTkyNDg4M30.e_40Xmy4Xvt66rDQXIw4C8DA0W48E2hYk5vRxXttiis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});