// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsuospbrtmpmgeypseku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzdW9zcGJydG1wbWdleXBzZWt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMTY2MTksImV4cCI6MjA3MTg5MjYxOX0.QEgy9colSKZ60UvA79w_NeLN6y7KYVPgFtJD0of3bPA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});